### ISSUE TITLE
Google Service Account

### ISSUE THREAD

**Issue by DEllingsworth** [lppkarl/GoogleCloudPrintApi#19]
Is it possible to use a Google Service Account?

The authorization would be a bit different I think.  Perhaps something like
https://github.com/RobertoBrandini/GoogleCloudPrint/blob/31c4e011dbd12ca5c53930bdc781156d90be09c6/GoogleCloudPrintService.cs#L294

**Comment by lppkarl** [comment]
@DEllingsworth it is possible we use Google Service Account as long as we provide the "cloudprint" scope & returns the access token but the integration with the "Google.Apis.Auth.OAuth2" have not yet implemented on this lib. 

It would be good if you could help to implement it, or I would do it later but i can't guarantee any time schedule

**Comment by awerber** [comment]
Hi,

There's code at https://github.com/io7/GoogleCloudPrint that uses a service account for many operations. But I don't think you can register a printer or issue a share invitation from a service account. I've found that once I register a non Google cloud ready printer, I cannot register any more. I can register all the Google Cloud ready printers I want, and do a manual share to the service account.

So, I've been trying some things to get the authorization code and pass that value into the code in this project. Specifically, I found code at https://developers.google.com/identity/sign-in/web/server-side-flow that appears to generate an authorization code. I pass that code to a REST service using an Ajax call, and that service calls the GenerateRefreshTokenAsync method using a redirect URL that is registered with my OAuth2 credentials (on the https://console.developers.google.com/apis/credentials/oauthclient page). But, I get a 401 (Unauthorized) error when I call GenerateRefreshTokenAsync. So, I'm pretty stuck trying to register non Google cloud ready printers.

I hope this helps you. 

If you know how to get a token using the code in this repository, please reply to this, or reach me through my repository at https://github.com/awerber/GCP_Service_Account, I've been working on this problem for 2 weeks now.

**Comment by karlwancl** [comment]
Closed for being inactive for a long time.
