### ISSUE TITLE
Error trying to register printer

### ISSUE THREAD

**Issue by awerber** [lppkarl/GoogleCloudPrintApi#21]
Hello again Karl,

I tried to register a printer by running your code in the GoogleCloudPrintApi.Samples project. I  substituted the client ID and client secret for my 'other' type account.

After trying to execute the line var googlePrinter = client.RegisterPrinterAsync(request).Result; from the Register Printer method, I get the following message from the base exception: FileNotFoundException: Could not load file or assembly 'System.Collections.NonGeneric, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Upon further investigation, I think the error ultimately comes from the GenerateAccessTokenAsync method in the GoogleOAuth2ProviderBase.cs file.

I tried to look for a version 4.1.0.0 of this DLL. The closest I could find is version 4.3. 

Again, any help would be greatly appreciated.

**Comment by lppkarl** [comment]
May I know what platform you are targeting? It's weird the lib uses ms beta package for operating. But at the time being, you may use the beta package from ms here: https://dotnet.myget.org/feed/dotnet-core-dev-api/package/nuget/System.Collections.NonGeneric/4.1.0-beta-devapi-24424-01

**Comment by awerber** [comment]
I got past the error by downloading .NET Core 2.0 and setting the target framework of the sample program to .NET Code 2.0.

I then deleted one of my local printers using the delete button at https://www.google.com/cloudprint#printers. Then I renamed one of your XML files under the xps directories using the name of one of my local printers. When I ran the code, the name of the printer showed up on my list of Cloud printers. But when I tried to print, a job was queued, but never printed. I should point out that the printer is a 'classic' printer.

I was able to register and use this printer when I got code from https://github.com/google/cloud-print-connector. But there are several manual steps when registering the printer using the connector.

I also have Google Cloud Print service running. Maybe that's connecting the printer in question to my computer and preventing proper registration. 

So, I have lots of stuff to try, but if you have an insight into how to get my printer working after using this register interface, I would greatly appreciate it.

**Comment by lppkarl** [comment]
The lib doesn‘t automatically redirect your printed job to your target printer. The proper way is to call the download interface, pull the job from Google cloud to the local server, and redirect the downloaded content to the printer through calling the print program (maybe a PDF viewer that takes doc as an arg for printing)

**Comment by awerber** [comment]
I see. I'm going to close this issue. Unfortunately, I don't quite understand how to get the registered printer to actually print from your reply. So, I'm going to open another issue.
